### PR TITLE
Use nextjs and nextra instead of Jekyll

### PR DESCRIPTION
**Pull request by bchapuis**
Jekyll is relatively limited when it comes to integrate advanced demonstrations in web pages. The goal of this PR is to explore the use of nextjs and nextra to create Baremaps' documentation web site. These technologies allow us to embed react components in the markdown and hence to nest advanced demonstrations in the documentation. The README contains instructions to run the web site locally. 

Any thought on this change? The publication pipeline has not yet been updated.

Screenshot 2023-03-01 at 17 07 07

### CODE REVIEW

**Comment by joshfischer1108** [comment]
I think I broke it 😆 
```
$ npm install && npm run dev
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
info  - automatically enabled Fast Refresh for 3 custom loaders
[nextra] Error compiling /Users/joshfischer/Source/apache/incubator-baremaps-site/pages/_app.mdx.
[nextra] Error compiling /Users/joshfischer/Source/apache/incubator-baremaps-site/pages/_app.mdx.
error - ./pages/_app.mdx
TypeError: String(...).replaceAll is not a function
wait  - compiling...
[nextra] Error compiling /Users/joshfischer/Source/apache/incubator-baremaps-site/pages/_app.mdx.
error - ./pages/_app.mdx
TypeError: String(...).replaceAll is not a function
wait  - compiling...
[nextra] Error compiling /Users/joshfischer/Source/apache/incubator-baremaps-site/pages/_app.mdx.
error - ./pages/_app.mdx
TypeError: String(...).replaceAll is not a function
```

**Comment by bchapuis** [comment]
Ahah, it works on my machine...

I have no idea where this replaceAll call come from. Which version of nodejs are you using? Mine is the following:

```bash
node --version
v18.12.1
```

**Comment by joshfischer1108** [comment]
That was it. Leave it to me to have my default node version at 14 🤦 .  I was able to run the new site locally and I love it. Looks super slick. + 1 to you, sir. 


Screen Shot 2023-03-01 at 11 47 35 AM

**Comment by bchapuis** [comment]
The [nextra/vercel](https://nextra.site) did a really good job and the template has sound defaults for a documentation web site. I hadn't tested the dark mode and I see that my subtitle needs some tuning.

**Comment by bchapuis** [comment]
@joshfischer1108 I merged this branch into main to test the deployment workflow and everything went smoothly. I guess we can keep this new version and improve it step by step. Similarly, do not hesitate to merge your changes if they improve the current status.

**Pull request merged**
